### ISSUE TITLE
Corrigir problema/warning apontado pelo SonarQube (2/6)

### ISSUE THREAD

**Issue by karolalencar** [karolalencar/ES2_2023-2_Hertzbeat#16]

**Comment by isarbela** [comment]
[Issue no Sonar](https://sonarcloud.io/project/issues?open=AY08gpbBFQg_WZgKfFiI&id=karolalencar_ES2_2023-2_Hertzbeat)
![image](https://github.com/karolalencar/ES2_2023-2_Hertzbeat/assets/50814645/37c5f7cc-a5a9-48e3-992c-6bea288bf5c2)

**Comment by isarbela** [comment]
[Sonar issue](https://sonarcloud.io/project/issues?open=AY08gpZDFQg_WZgKfFgK&id=karolalencar_ES2_2023-2_Hertzbeat)

![image](https://github.com/karolalencar/ES2_2023-2_Hertzbeat/assets/50814645/b42200d1-2bef-4cd8-b71e-47617fea64b1)
